### PR TITLE
Add PR template

### LINKED ISSUE #325: Create a PR template
Turns out [you can define PR templates](https://help.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository)

Lets make one.  It should include blocked sections for:

(1) How to test this PR
(2) Configuration required

### PR DESCRIPTION
**Pull request by slifty**
This introduces a template for future pull requests, this should help us all remember to provide the important information when opening PRs.

Note: some concepts are borrowed from [this template](https://github.com/nvaccess/nvda/blob/master/.github/PULL_REQUEST_TEMPLATE.md)

Resolves #325

### CODE REVIEW

**Comment by reefdog** [comment]
This feels kinda heavy. Maybe I'm just header-averse, but I feel like the boilerplate is gonna get in the way of just reading the thing. Lemme send this comment, then play around for a sec.

**Comment by reefdog** [comment]
- **Status:** READY | IN DEVELOPMENT | HOLD
- **Requires migrations?** YES | NO
- **Requires package updates?** YES | NO
- **Requires new configuration?** YES | NO

## Description

A few sentences describing the overall goals of the pull request's commits…

### Related Issues

List related / resolved issues

### Remaining TODOs

- [ ] Tests
- [ ] Documentation

## Steps to Test

Outline the steps to test or reproduce the PR here…

```sh
yarn test
```

## Deploy Notes

Write any additional notes/instructions here…

**Comment by reefdog** [comment]
@slifty What do you think about ☝️?

**Comment by slifty** [comment]
Yeah good point -- also, we are using labels for requires migration / package updates so I think including it in the template may be redundant.

Will take your proposed tweaks and continue to iterate.

**Comment by reefdog** [comment]
Yeah, I like the use of the labels for sure. I took from your "Requires migrations" bit that you wanted to surface those in the PR body as well; I'm fine either way (with a preference for the labels).

**Comment by slifty** [comment]
@reefdog made some other tweaks, I think this is much better!  Ready for another review

**Pull request merged**
