### PR TITLE
Remove backfill

### LINKED ISSUE #371: Remove backfill
We talked about a more robust version of this in #366 but for now we want to just remove the backfill in the current alerts.  This means that we will *only* show claims by known speakers, and if they aren't in the list they won't appear.

### PR DESCRIPTION
**Pull request by slifty**
## Description

This PR removes any claims from the national newsletter that are NOT known speaker claims.

## Due Diligence Checklist
- [x] Tests
- [x] Documentation
- [x] Consolidated commits
- [x] Relevant labels assigned

## Steps to Test
1. `yarn test`

## Deploy Notes
None

## Related Issues
Resolves #371

### CODE REVIEW

**Comment by slifty** [comment]
@reefdog SQL optimization is a deep dark beast of its own -- you are correct that the optimizer will handle that kind of thing for me regardless of order.

**Comment by slifty** [comment]
I also ran a local email test and it seems to be working -- merging.

**Comment by reefdog** [comment]
Dan I famously have no idea how to program or even read/write.

**Comment by slifty** [comment]
I'm gonna update your wikipedia page.

**Comment by reefdog** [comment]
I'll have no way of knowing!

**Pull request merged**
